### ISSUE TITLE
肖国彧帅吗？

### ISSUE THREAD

**Issue by lixiaoyiSHAWN** [lixiaoyiSHAWN/useless-repository#2]
哈哈哈哈....这个机器人太好玩了lol

**Comment by xiaoguoyu** [comment]
那是当然了

**Comment by lixiaoyiSHAWN** [comment]
az

**Comment by lixiaoyiSHAWN** [comment]
此人帅照
![share](https://user-images.githubusercontent.com/65407504/108522276-9fece580-7307-11eb-9d67-fa8cdcd1cfc8.jpg)

**Comment by xiaoguoyu** [comment]
WTF你别暴露我的个人信息
